### ISSUE TITLE
Update 'Pocket' iPhone app image above fold

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#8]
- [ ] Replace image with three cards, similar to the cards lower in the page, in Now is the time to build your portfolio.
- [ ] One gene input card
- [ ] One enrichment card
- [ ] One network card

**Comment by chrtannus** [comment]
I think we should have a simpler hero image instead of input cards because:
a) we don't want the hero page to look too complex or intimidating
b) we want the focus to be the "get started" button, where the app will suggest the best tool for the user's input data, etc

Here's a suggestion (subset network from GeneMANIA):

<img width="1376" alt="hero-fig" src="https://github.com/cytoscape/cytoscape-home/assets/989686/86f4924b-a7d2-4894-b51c-0f0b79204f3b">

<br><br>

- hover any node to show its label
- hover the central node to also show a simulated tooltip
  <img width="655" alt="hero-fig-hover" src="https://github.com/cytoscape/cytoscape-home/assets/989686/5082a241-d700-4453-a85a-83d1cc3fec81">

**Comment by maxkfranz** [comment]
Great point

**Comment by chrtannus** [comment]
Dexter suggested that by clicking at the figure (or a node) it could open a network in Cytoscape Web.
I think this is a great idea.
